const data = {
    allStudents : [
        {
            id : '1',
            name : 'Vijay',
            position: 'Web Developer',
            rollNo : '16UK1A05H1',
            contact : 33699365,
            email : 'vijay@gmail.com',
            fatherName : "Sadanandam",
            department : 'CSE',
            college : 'Sun Shine College',
            avergaeMarks : '71%',
            project : "Emotion Recognition on Twitter"
        },  
        {
            id : '2',
            name : 'Ajat',
            position: 'UI Developer',
            rollNo : '16UK1A05H2',
            contact : 336433555,
            email : 'ajay@gmail.com',
            fatherName : "Sadhi",
            department : 'CSE',
            college : 'Sun Shine College',
            avergaeMarks : '78%',
            project : "facebook Clone"
        },  
        {
            id : '3',
            name : 'Raj',
            position: 'Java Developer',
            rollNo : '16UK1A05H3',
            contact : 336543,
            email : 'raj@gmail.com',
            fatherName : "Ramaiah",
            department : 'CSE',
            college : 'Sun Shine College',
            avergaeMarks : '81%',
            project : "React Developer"
        },  
        {
            id : '4',
            name : 'Jay',
            position: 'Signal Analyst',
            rollNo : '16UK1A05H4',
            contact : 33699365,
            email : 'jay@gmail.com',
            fatherName : "Laxman",
            department : 'EEE',
            college : 'Sun Shine College',
            avergaeMarks : '71%',
            project : "Micro-Singals Analysis"
        },  
        {
            id : '5',
            name : 'vicky',
            position: 'Python Developer',
            rollNo : '16UK1A05H5',
            contact : 33699365,
            email : 'vicky@gmail.com',
            fatherName : "Ramulu",
            department : 'CSE',
            college : 'Sun Shine College',
            avergaeMarks : '71%',
            project : "Neflix clone"
        },  
        {
            id : '6',
            name : 'Sathyam',
            position: 'Mechanical Engineer',
            rollNo : '16UK1A05H6',
            contact : 33699365,
            email : 'sathyam@gmail.com',
            fatherName : "Vikram",
            department : 'Mechanical',
            college : 'Sun Shine College',
            avergaeMarks : '71%',
            project : "Based on Auto-Cad project"
        },  
        {
            id : '7',
            name : 'madhu',
            position: 'micro-waves Analyst',
            rollNo : '16UK1A05H7',
            contact : 33645765,
            email : 'madhu@gmail.com',
            fatherName : "Ravi",
            department : 'ECE',
            college : 'Sun Shine College',
            avergaeMarks : '88%',
            project : "Micro-Wave Frequencies"
        },  
        {
            id : '8',
            name : 'Ravi',
            position: 'Web Developer',
            rollNo : '16UK1A05H8',
            contact : 33699365,
            email : 'vijay@gmail.com',
            fatherName : "Teja",
            department : 'CSE',
            college : 'Sun Shine College',
            avergaeMarks : '71%',
            project : "Emotion Recognition on Twitter"
        },  
        {
            id : '9',
            name : 'Babu',
            position: 'Angular Developer',
            rollNo : '16UK1A05H9',
            contact : 33699365,
            email : 'babu@gmail.com',
            fatherName : "Srikanth",
            department : 'CSE',
            college : 'Sun Shine College',
            avergaeMarks : '71%',
            project : "Developed projects with Angular"
        },  
        {
            id : '10',
            name : 'Vijji',
            position: 'Game Developer',
            rollNo : '16UK1A05H10',
            contact : 33699365,
            email : 'vijji@gmail.com',
            fatherName : "S.Raad",
            department : 'CSE',
            college : 'Sun Shine College',
            avergaeMarks : '71%',
            project : "Build a online game"
        },  
    ],
}
export default data;